# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='No image', upload_to='insta/'),
        ),
    ]
