# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='No image', upload_to='instas/'),
        ),
    ]
