# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20181006_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prof_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
