# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_auto_20181007_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uimage',
            new_name='image',
        ),
    ]
