# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['posted_date']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='pub_date',
            new_name='posted_date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='image',
            name='posted_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.TextField(),
        ),
    ]
